### ISSUE TITLE
[상품] 재고 수량 부족 알림 기능 개발, 시드 데이터 추가 및 리팩토링

### ISSUE THREAD

**Issue by bongdaehyun** [dev-wonny/coopang#118]
## TODO
* [ ] 재고 수량 10개 이하 시 ai&noti 서버에 메시지 전달
* [ ] 사용자 테스트를 위한 시드 데이터 추가
* [ ] DDD 구조에 맞춰 리팩토링 및 중복된 코드 수정
* [ ] 메소드별 주석 추가
## 예상 개발 기간
* 24.10.11 ~ 24.10.13 (3일)
