### ISSUE TITLE
[CICD] Coopang Project 배포 과정

### ISSUE THREAD

**Issue by jiminchur** [dev-wonny/coopang#165]
## Todo
* [ ] 배포용 브랜치 하나 추가 생성하기 (#00-DEV-cicd)
* [ ] 폴더가 변경사항이 있을 경우에 따로 적용하기
* [ ] docker로 빌드를 한뒤 ec2에서 빌드한 부분만 따로 재 배포 하기

**Comment by jiminchur** [comment]
## path 설정을 통한 서버별 독립적으로 배포하기
```
name: Deploy to EC2

on:
  push:
    branches:
      - #DEV-cicd # 배포할 브랜치 설정.
    paths:
      - ./BOOT/gateway/**
      - ./BOOT/user/**
      - ./BOOT/hub/**
      - ./BOOT/delivery/**
      - ./BOOT/order/**
      - ./BOOT/product/**
      - ./CLOUD/eureka/**
      - ./BOOT/ainoti/**
jobs:
  build:
    runs-on: ubuntu-latest
```

**Comment by jiminchur** [comment]
## 배포용 application.yml파일 설정하기
* if 문을 통해 해당 폴더 이하에 commit이 이루어 지면 그 서버만 yml를 등록하고 빌드하기
```
      - name: Generate application.yml
        run: |
          declare -A services=(
            ["gateway"]="${{ secrets.GATEWAY_YML }}"
            ["user"]="${{ secrets.USER_YML }}"
            ["hub"]="${{ secrets.HUB_YML }}"
            ["delivery"]="${{ secrets.DELIVERY_YML }}"
            ["order"]="${{ secrets.ORDER_YML }}"
            ["product"]="${{ secrets.PRODUCT_YML }}"
            ["eureka"]="${{ secrets.EUREKA_YML }}"
            ["ainoti"]="${{ secrets.AINOTI_YML }}"
          )
          for service in "${!services[@]}"; do
            if [[ "${{ github.event.head_commit.message }}" == *"$service"* ]]; then
              echo "${services[$service]}" > "./BOOT/$service/src/main/resources/application.yml"
              ./gradlew BOOT:$service:build -x test   
            fi
          done
```

**Comment by jiminchur** [comment]
## 도커에 이미지 빌드하기
```
- name: Build and Push Docker Images to Docker Hub
        run: |
          for service in "gateway" "user" "hub" "delivery" "order" "product" "eureka" "ainoti"; do
            if [[ "${{ github.event.head_commit.message }}" == *"$service"* ]]; then
              # Gradle 빌드
              ./gradlew BOOT:$service:build -x test
              # Docker 이미지 빌드
              docker build -t your-dockerhub-username/$service:latest ./BOOT/$service
              # Docker 이미지 푸시
              docker push your-dockerhub-username/$service:latest
            fi
          done
```

**Comment by jiminchur** [comment]
## EC2에서 변화가 일어난 부분만 중지, 이미지 풀, 시작하기
```
      - name: Manage Docker Compose on EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > foodtogo.pem
          chmod 600 foodtogo.pem
          ssh -i foodtogo.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            for service in "gateway" "user" "hub" "delivery" "order" "product" "eureka" "ainoti"; do
              if [[ "${{ github.event.head_commit.message }}" == *"$service"* ]]; then
                echo "Stopping and removing containers for $service"
                docker-compose -f "/path/to/$service/docker-compose.yml" down
                echo "Pulling the latest image for $service"
                docker-compose -f "/path/to/$service/docker-compose.yml" pull
                echo "Starting containers for $service"
                docker-compose -f "/path/to/$service/docker-compose.yml" up -d
              fi
            done
          EOF

```

**Comment by jiminchur** [comment]
## ❗️ARM 아키텍처와 AMD 아키텍처 간의 플랫폼 불일치 이슈
* Docker Buildx로 특정 플랫폼에 맞는 이미지로 빌드 하였음
```
docker buildx build --platform linux/amd64 -t ttlcc13/eureka:latest ./CLOUD/eureka/ --load
```

**Comment by jiminchur** [comment]
## DockerHub에 이미지 빌드 완료
![스크린샷 2024-10-22 오전 12 40 07](https://github.com/user-attachments/assets/f63170c6-65f3-4164-a175-d1d421af6907)

**Comment by jiminchur** [comment]
## ❗️loki와의 연결 이슈
```
15:43:58,070 |-ERROR in com.github.loki4j.client.pipeline.AsyncBufferPipeline@233f01c7 - Retry #2. Error while sending Batch #1d01912b4f3c (337,862 bytes) to Loki (http://localhost:3100/loki/api/v1/push) java.net.ConnectException
at java.net.ConnectException
```

**Comment by jiminchur** [comment]
## 배포 완료
![스크린샷 2024-10-22 오전 1 35 10](https://github.com/user-attachments/assets/82cd21ef-2f19-45b5-a582-6b30990682da)
