### ISSUE TITLE
[상품서버] 내부통신 및 카프카 설정, 접근권한별로 구분

### ISSUE THREAD

**Issue by bongdaehyun** [dev-wonny/coopang#83]
## TODO
* [x] 필요한 내부통신 연결하기
* [x] 카프카 이벤트 및 토픽 설정
* [x] 접근권한 별로 조회 및 상품 관리 구분
* [x] 상품 조회 시 캐싱추가
## 예상 개발 기간(내부통신이 만들어지면 연결해야되므로 일단 대기중)
* 24.10.07 ~ 24.10.09 (3일)
